import random

motivational_qoutes=["Unlock Your Potential Inspiring Quotes to Ignite Your Fire 🔥",
"Words of Wisdom Embrace Life with These Powerful Quotes 💫",
"Motivation Station Fuel Your Dreams with Inspirational Quotes 🚀",
"Rise and Shine Let These Quotes Brighten Your Day ☀️",
"Dream Big, Achieve Big Unleash Your Inner Champion 🏆",
"Wisdom that Transforms Lives Join the Quote Revolution 🌟",
"Your Daily Dose of Motivation Subscribe for Quote Bliss 💫",
"Ignite Your Passion with Inspirational Quotes Hit Subscribe 🔥",
"Quotes that Empower Join Our Community of Dreamers 💪",
"Elevate Your Mind Click to Discover Life's Greatest Quotes ✨",
"Inspiring Quotes for Success Don't Miss a Single Upload! 🚀",
"Be Inspired, Be Subscribed Motivational Quotes Awaits You 😊",
"Change Your Life with the Power of Words Subscribe Now! 💼",
"Positive Vibes Only Join Our Quote Family Today! 😄",
"Quotes that Spark Joy Be Part of Our Inspirational Journey 🌈",
"Daily Motivation Delivered Hit Subscribe for Quote Goodness! 📲",
"Empowering Quotes for a Fulfilling Life Click to Stay Inspired! 💫",
"Subscribe for Success Life-Changing Quotes Await You 🏅",
"Join the Quote Revolution Click to Transform Your Mindset 🌟",
"Quotes to Uplift Your Spirit Subscribe and Soar High 🦅",
"Inspiration Guaranteed Subscribe for a Better Tomorrow! 🌅",
"Your Source of Positivity Hit Subscribe for Quote Magic! ✨",
"Unlock Your Potential Join Our Motivated Community Today 🔓",
"Daily Quotes for Success Click to Unleash Your Inner Champion 🚀",
"Unlock the Power of Inspiration Life-Changing Quotes Inside! 🔥",
"Wisdom that Transforms Lives Join the Quote Revolution 🌟",
"Your Daily Dose of Motivation Subscribe for Quote Bliss 💫",
"Ignite Your Passion with Inspirational Quotes Hit Subscribe 🔥",
"Quotes that Empower Join Our Community of Dreamers 💪",
"Elevate Your Mind Click to Discover Life's Greatest Quotes ✨",
"Inspiring Quotes for Success Don't Miss a Single Upload! 🚀",
"Be Inspired, Be Subscribed Motivational Quotes Awaits You 😊",
"Change Your Life with the Power of Words Subscribe Now! 💼",
"Positive Vibes Only Join Our Quote Family Today! 😄",
"Quotes that Spark Joy Be Part of Our Inspirational Journey 🌈",
"Daily Motivation Delivered Hit Subscribe for Quote Goodness! 📲",
"Empowering Quotes for a Fulfilling Life Click to Stay Inspired! 💫",
"Subscribe for Success Life-Changing Quotes Await You 🏅",
"Join the Quote Revolution Click to Transform Your Mindset 🌟",
"Quotes to Uplift Your Spirit Subscribe and Soar High 🦅",
"Inspiration Guaranteed Subscribe for a Better Tomorrow! 🌅",
"Your Source of Positivity Hit Subscribe for Quote Magic! ✨",
"Unlock Your Potentia  Join Our Motivated Community Today 🔓",
"Daily Quotes for Success Click to Unleash Your Inner Champion 🚀",]
number=random.randint(0,len(motivational_qoutes))
print(motivational_qoutes[number])

print(random.random())